package github_stats

import "encoding/json"


type AutoGenerated struct {
	Data struct {
		User struct {
			ContributionsCollection struct {
				ContributionCalendar struct {
					TotalContributions int `json:"totalContributions"`
					Weeks              []struct {
						FirstDay         string `json:"firstDay"`
						ContributionDays []struct {
							Date              string `json:"date"`
							Weekday           int    `json:"weekday"`
							ContributionCount int    `json:"contributionCount"`
							Color             string `json:"color"`
						} `json:"contributionDays"`
					} `json:"weeks"`
				} `json:"contributionCalendar"`
			} `json:"contributionsCollection"`
		} `json:"user"`
	} `json:"data"`
}

func Github_stats(userName string) (AutoGenerated, error){
	res, err := Get_github_contrib(userName)
	if err != nil {
		return AutoGenerated{}, err
	}
	
	var a AutoGenerated
  if err := json.Unmarshal(res, &a); err != nil {
		return AutoGenerated{}, nil
	}

	return a, nil
}
